#!/bin/bash

### ###############
##
#	$ ln -s <PATH_TO_THIS_FILE> $HOME/.shelladdonrc
#	put "source $HOME/.shelladdonrc" at the end of shells ".rc"
#	e.g. ~/.zshrc or ~/.bashrc
#
###

function shelladdon {
	action=${@[*]:1:1}

	if [ "$action" = "enable" ]; then
		for script in "$@"; do
			if [ -f "$HOME/.sh.d/conf-available/$script.sh" ] && [ ! -L "$HOME/.sh.d/conf-enabled/$script.sh" ]; then
				ln -s "$HOME/.sh.d/conf-available/$script.sh" "$HOME/.sh.d/conf-enabled/$script.sh" > /dev/null
				source "$HOME/.sh.d/conf-enabled/$script.sh"
			fi
		done

	elif [ "$action" = "disable" ]; then
		for script in "$@"; do
			if [ -f "$HOME/.sh.d/conf-available/$script.sh" ] && [ -L "$HOME/.sh.d/conf-enabled/$script.sh" ]; then
				rm "$HOME/.sh.d/conf-enabled/$script.sh"
			fi
		done

	elif [ "$action" = "list" ]; then
		echo "available scripts (+enabled/-disabled)"
		for available in "$HOME/.sh.d/conf-available/"*; do
			SCRIPTNAME=$(basename $available)
			if [ -f "$HOME/.sh.d/conf-available/$SCRIPTNAME" ] && [ -L "$HOME/.sh.d/conf-enabled/$SCRIPTNAME" ]; then
				echo -e "\t+ ${SCRIPTNAME:0:-3}"
			elif [ -f "$HOME/.sh.d/conf-available/$SCRIPTNAME" ]; then
				echo -e "\t- ${SCRIPTNAME:0:-3}"
			fi
		done

	elif [ "$action" = "init" ]; then
		if [ ! -d  "$HOME"/.sh.d/conf-enabled ]; then
			mkdir -p "$HOME"/.sh.d/conf-enabled
		fi
		if [ $(find "$HOME"/.sh.d/conf-enabled -name "*.sh" | wc -l) = 0 ]; then
			return 0
		fi
		for enabled in "$HOME/.sh.d/conf-enabled/"*; do
			if [ -f "$enabled" ]; then
				source $enabled
			else
				rm "$enabled"
			fi
		done
	else
		echo "usage: shelladdon [enable|disable|init] [<NAME>]"
		return 1
	fi
}

### ###############
##
#	load all scripts
#
###
shelladdon init
