#!/bin/bash

### ###############
## 
#	$ ln -s <PATH_TO_THIS_FILE> $HOME/.shelladdonrc
#	put "source $HOME/.shelladdonrc" at the end of shells ".rc"
#	e.g. ~/.zshrc or ~/.bashrc 
#
###

shelladdonload() {
	if [ $(ls -1 "$HOME"/.sh.d/conf-enabled | wc -w) -eq 0 ]; then
		return
	fi
	for enabled in "$HOME"/.sh.d/conf-enabled/*; do
		source $enabled
	done
}
shelladdonlist() {
	echo "available scripts (+enabled/-disabled)"
	for available in "$HOME"/.sh.d/conf-available/*; do
		SCRIPTNAME=$(basename $available)
		if [ -L "$HOME"/.sh.d/conf-enabled/"$SCRIPTNAME" ]; then
			echo -e "\t+ $SCRIPTNAME"
		else
			echo -e "\t- $SCRIPTNAME"
		fi
	done
}
shelladdonenable() {
	ln -s "$HOME"/.sh.d/conf-available/"$1" "$HOME"/.sh.d/conf-enabled/"$1"
}
shelladdondisable() {
	if [ -L "$HOME"/.sh.d/conf-enabled/"$1" ]; then
		rm "$HOME"/.sh.d/conf-enabled/"$1"
	fi
}

shelladdon() {
	if [ "$1" = "enable" ]; then
		shelladdondisable "$2"
		shelladdonenable "$2"
		shelladdonload
	elif [ "$1" = "disable" ]; then
		shelladdondisable "$2"
		shelladdonload
	elif [ "$1" = "list" ]; then
		shelladdonlist
	elif [ "$1" = "init" ]; then
		shelladdonload
	else
		echo "usage: shelladdon [enable|disable|init] [<NAME>]"
		read && return
	fi
}

### ###############
## 
#	load all scripts
#
###
shelladdonload
